# Makefile automatically generated by ghdl
# Version: GHDL 5.1.1 (tarball) [Dunoon edition] - GCC 15.2.1 code generator
# Command used to generate this makefile:
# ghdl --gen-makefile tb_riscVR > Makefile

GHDL=ghdl
BUILD=build
TB_FILE=tb_riscV

GHDLFLAGS= --workdir=$(BUILD)
GHDLRUNFLAGS= --wave=sim/$(TB_FILE).ghw

TARGET = /usr/lib/ghdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/ieee/v93/std_logic_1164-body.o /usr/lib/ghdl/ieee/v93/numeric_std.o
TARGET += /usr/lib/ghdl/ieee/v93/numeric_std-body.o /usr/lib/ghdl/std/v93/textio.o /usr/lib/ghdl/std/v93/textio-body.o
TARGET += $(TB_FILE).o RiscV_package.o riscV.o ALU.o controleur.o PC.o IMEM.o REG.o Imm_ext.o RI_mux.o DMEM.o load_jump_mux.o
TARGET += LM.o SM.o BC.o B_mux.o

DEPENDANCES = /usr/lib/ghdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/ieee/v93/numeric_std.o

# Default target
all: $(TB_FILE)

# Elaboration target
$(TB_FILE): $(TARGET)
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: $(TB_FILE)
	$(GHDL) -r $(TB_FILE) $(GHDLRUNFLAGS)

# Launch simulation
sim: sim/$(TB_FILE).ghw
	gtkwave sim/$(TB_FILE).ghw

# Clean build and simulation files
clean:
	rm build/* sim/* tb_*

# Targets to analyze files
/usr/lib/ghdl/ieee/v93/std_logic_1164.o: /usr/lib/ghdl/ieee/v93/../../src/ieee/v93/std_logic_1164.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/ieee/v93/std_logic_1164-body.o: /usr/lib/ghdl/ieee/v93/../../src/ieee/v93/std_logic_1164-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/ieee/v93/numeric_std.o: /usr/lib/ghdl/ieee/v93/../../src/ieee/v93/numeric_std.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/ieee/v93/numeric_std-body.o: /usr/lib/ghdl/ieee/v93/../../src/ieee/v93/numeric_std-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/std/v93/textio.o: /usr/lib/ghdl/std/v93/../../src/std/v93/textio.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/std/v93/textio-body.o: /usr/lib/ghdl/std/v93/../../src/std/v93/textio-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
$(TB_FILE).o: testbench/$(TB_FILE).vhd
	$(GHDL) -a $(GHDLFLAGS) $<
RiscV_package.o: source/RiscV_package.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
riscV.o: source/riscV.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
ALU.o: source/ALU.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
controleur.o: source/controleur.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
PC.o: source/PC.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
IMEM.o: source/IMEM.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
REG.o: source/REG.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
Imm_ext.o: source/Imm_ext.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
RI_mux.o: source/RI_mux.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
DMEM.o: source/DMEM.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
load_jump_mux.o: source/load_jump_mux.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
LM.o: source/LM.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
SM.o: source/SM.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
BC.o: source/BC.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
B_mux.o: source/B_mux.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
/usr/lib/ghdl/ieee/v93/std_logic_1164.o:
/usr/lib/ghdl/ieee/v93/std_logic_1164-body.o:  /usr/lib/ghdl/ieee/v93/std_logic_1164.o
/usr/lib/ghdl/ieee/v93/numeric_std.o:  /usr/lib/ghdl/ieee/v93/std_logic_1164.o
/usr/lib/ghdl/ieee/v93/numeric_std-body.o:  /usr/lib/ghdl/ieee/v93/numeric_std.o
/usr/lib/ghdl/std/v93/textio.o:
/usr/lib/ghdl/std/v93/textio-body.o:  /usr/lib/ghdl/std/v93/textio.o
$(TB_FILE).o:           $(DEPENDANCES) /usr/lib/ghdl/std/v93/textio.o
RiscV_package.o:        $(DEPENDANCES)
riscV.o:                $(DEPENDANCES) RiscV_package.o
ALU.o:                  $(DEPENDANCES)
controleur.o:           $(DEPENDANCES)
PC.o:     			    $(DEPENDANCES)
IMEM.o:     			$(DEPENDANCES) /usr/lib/ghdl/std/v93/textio.o
REG.o: 					$(DEPENDANCES)
Imm_ext.o:              $(DEPENDANCES)
RI_mux.o:               $(DEPENDANCES)
DMEM.o:                 $(DEPENDANCES) /usr/lib/ghdl/std/v93/textio.o
load_jump_mux.o:        $(DEPENDANCES)
LM.o:                   $(DEPENDANCES)
SM.o:                   $(DEPENDANCES)
BC.o:                   $(DEPENDANCES)
B_mux.o:                $(DEPENDANCES)
